## Encoding vs Embeddings
**Encoding:** We need to represent our non-numerical, multimodal data as numbers so we can create models out of them.  
**Embeddings** We need a way to store the data we have encoded and have the ability to perform mathematical functions in an optimized way on them. We store encodings as vectors, usually floating-point representations.

![](images/embedding_method_solution_space.png)

In [1]:
# !pip install scikit-learn

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
import numpy as np


corpus = [
    "cat sat on the mat",
    "the dog chased the rabbit",
    "cat ate fish",
    "dogs and cats are friends",
    "a fish swims in the pond",
    "beer loves to sleep on the grass",
    "lion asked another lion",
    "the music is loud"
]

print("Corpus:")
for i, doc in enumerate(corpus, 1):
    print(f"{i}. {doc}")

Corpus:
1. cat sat on the mat
2. the dog chased the rabbit
3. cat ate fish
4. dogs and cats are friends
5. a fish swims in the pond
6. beer loves to sleep on the grass
7. lion asked another lion
8. the music is loud

# Count based methods

## Bag of words

In [2]:
count_vec = CountVectorizer()
X_multi = count_vec.fit_transform(corpus)

df_multi = pd.DataFrame(X_multi.toarray(), columns=count_vec.get_feature_names_out())
print("Document-Term Matrix (Multi-hot):")
df_multi

Document-Term Matrix (Multi-hot):

,and,another,are,asked,ate,beer,cat,cats,chased,dog,...,mat,music,on,pond,rabbit,sat,sleep,swims,the,to
0,0,0,0,0,0,0,1,0,0,0,...,1,0,1,0,0,1,0,0,1,0
1,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,1,0,0,0,2,0
2,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,1,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,1,1
6,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

## TF-IDF vectorization

In [3]:
# ---------------------------------------------------------------
# 4. TF–IDF document-term matrix
# ---------------------------------------------------------------
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(corpus)

df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vec.get_feature_names_out())
print("Document-Term Matrix (TF-IDF):")
df_tfidf.round(3)

Document-Term Matrix (TF-IDF):

,and,another,are,asked,ate,beer,cat,cats,chased,dog,...,mat,music,on,pond,rabbit,sat,sleep,swims,the,to
0,0.000,0.000,0.000,0.000,0.000,0.000,0.435,0.000,0.000,0.000,...,0.518,0.000,0.435,0.000,0.000,0.518,0.000,0.000,0.291,0.000
1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.484,0.484,...,0.000,0.000,0.000,0.000,0.484,0.000,0.000,0.000,0.544,0.000
2,0.000,0.000,0.000,0.000,0.645,0.000,0.540,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,0.447,0.000,0.447,0.000,0.000,0.000,0.000,0.447,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.499,0.000,0.000,0.000,0.499,0.280,0.000
5,0.000,0.000,0.000,0.000,0.000,0.408,0.000,0.000,0.000,0.000,...,0.000,0.000,0.342,0.000,0.000,0.000,0.408,0.000,0.229,0.408
6,0.000,0.408,0.000,0.408,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
7,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.549,0.000,0.000,0.000,0.000,0.000,0.000,0.308,0.000

## Compare document similarity

In [4]:

from sklearn.metrics.pairwise import cosine_similarity


# Compare 2 documents
doc_0 = [corpus[0]]  # cat sat on the mat
doc_2 = [corpus[2]] # cat ate fish
doc_7 = [corpus[7]] # the music is loud

# Vectorize both ways
multi_hot_pair = count_vec.transform(doc_0 + doc_2 + doc_7)
tfidf_pair = tfidf_vec.transform(doc_0 + doc_2 + doc_7)

sim_multi = cosine_similarity(multi_hot_pair)
sim_tfidf = cosine_similarity(tfidf_pair)


pd.DataFrame([[round(sim_multi[0,1],3), round(sim_multi[0,2],3)], [round(sim_tfidf[0,1],3), round(sim_tfidf[0,2], 3)]])

print(f"CountVectorizer(overlapping cat vs overlapping(the)): {round(sim_multi[0,1],3), round(sim_multi[0,2],3)}")

print(pd.DataFrame(sim_multi))

print(f"TF-IDF(overlapping cat vs overlapping(the)): {round(sim_tfidf[0,1],3), round(sim_tfidf[0,2], 3)}")
print(pd.DataFrame(sim_tfidf))

CountVectorizer(overlapping cat vs overlapping(the)): (np.float64(0.258), np.float64(0.224))
          0         1         2
0  1.000000  0.258199  0.223607
1  0.258199  1.000000  0.000000
2  0.223607  0.000000  1.000000
TF-IDF(overlapping cat vs overlapping(the)): (np.float64(0.235), np.float64(0.09))
          0         1        2
0  1.000000  0.234842  0.08971
1  0.234842  1.000000  0.00000
2  0.089710  0.000000  1.00000

## Extract Term vectors

In [5]:
print(X_tfidf.shape)
pd.DataFrame(X_tfidf.T.toarray(), index=count_vec.get_feature_names_out())
# pd.DataFrame(X_tfidf.T@X_tfidf.toarray(), columns=count_vec.get_feature_names_out())

(8, 29)

,0,1,2,3,4,5,6,7
and,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
another,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000
are,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
asked,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000
ate,0.000000,0.000000,0.644859,0.000000,0.000000,0.000000,0.000000,0.000000
beer,0.000000,0.000000,0.000000,0.000000,0.000000,0.407658,0.000000,0.000000
cat,0.434536,0.000000,0.540443,0.000000,0.000000,0.000000,0.000000,0.000000
cats,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
chased,0.000000,0.484496,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
dog,0.000000,0.484496,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
dogs,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
fish,0.000000,0.000000,0.540443,0.000000,0.418131,0.000000,0.000000,0.000000
friends,0.000000,0.000000,0.000000,0.447214,0.000000,0.000000,0.000000,0.000000
grass,0.000000,0.000000,0.000000,0.000000,0.000000,0.407658,0.000000,0.000000
in,0.000000,0.000000,0.000000,0.000000,0.498916,0.000000,0.000000,0.000000
is,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.549233
lion,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.816497,0.000000
loud,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.549233
loves,0.000000,0.000000,0.000000,0.000000,0.000000,0.407658,0.000000,0.000000
mat,0.518492,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
music,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.549233
on,0.434536,0.000000,0.000000,0.000000,0.000000,0.341649,0.000000,0.000000
pond,0.000000,0.000000,0.000000,0.000000,0.498916,0.000000,0.000000,0.000000
rabbit,0.000000,0.484496,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
sat,0.518492,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
sleep,0.000000,0.000000,0.000000,0.000000,0.000000,0.407658,0.000000,0.000000
swims,0.000000,0.000000,0.000000,0.000000,0.498916,0.000000,0.000000,0.000000
the,0.291014,0.543867,0.000000,0.000000,0.280027,0.228806,0.000000,0.308268
to,0.000000,0.000000,0.000000,0.000000,0.000000,0.407658,0.000000,0.000000

## Dense vector representations

In [6]:
# !pip install gensim
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

### Inspect vocabulary

In [7]:
# inspect vocabulary
for index, word in enumerate(wv.index_to_key):
    if index == 10:
        break
    print(f"word #{index}/{len(wv.index_to_key)} is {word}")

word #0/3000000 is </s>
word #1/3000000 is in
word #2/3000000 is for
word #3/3000000 is that
word #4/3000000 is is
word #5/3000000 is on
word #6/3000000 is ##
word #7/3000000 is The
word #8/3000000 is with
word #9/3000000 is said

### Check pairwise similarity

In [8]:

pairs = [
    ('car', 'minivan'),   # a minivan is a kind of car
    ('car', 'bicycle'),   # still a wheeled vehicle
    ('car', 'airplane'),  # ok, no wheels, but still a vehicle
    ('car', 'cereal'),    # ... and so on
    ('car', 'communism'),
]
for w1, w2 in pairs:
    print(f"{w1}|{w2}|{wv.similarity(w1, w2)}")

car|minivan|0.6907036900520325
car|bicycle|0.5364484190940857
car|airplane|0.42435577511787415
car|cereal|0.13924746215343475
car|communism|0.05820293352007866

### Answer analogy questions

In [16]:

# king + woman - man = ?
# man:woman::king:?
print(wv.most_similar(positive=['king', 'woman'], negative=['man'], topn=2))

# wv['Timbers'] - wv['Portland'] + wv['Seattle'] = ?
print(wv.most_similar(positive=['Timbers', 'Seattle'], negative=['Portland'], topn=2))

# wv['Einstein'] - wv['physics'] + wv['classical_music'] = ?
print(wv.most_similar(positive=['Einstein', 'classical_music'], negative=['physics'], topn=2))

[('queen', 0.7118193507194519), ('monarch', 0.6189674139022827)]
[('Sounders', 0.627106249332428), ('Sounders_FC', 0.6018840074539185)]
[('Mozart', 0.5742169618606567), ('Beethoven', 0.5615471601486206)]

### How to train your own embedding model

<img src="images/word2vec_training.jpg" width=400 />

### Train your own word2vec model: using gensim

In [17]:
import re
al_regex = re.compile(r"[^a-zA-Z]")
class MyCorpus:
    """An iterator that yields sentences (lists of str)."""

    def __iter__(self):
        corpus_path = "data/mahabharat_gutenberg_lemmatized_sents.txt"
        with open(corpus_path) as fp:
            for line in fp.readlines():
                tokens = line.split()
                tokens = [al_regex.sub('', token) for token in tokens]
                yield tokens

In [18]:
import time
import gensim.models

sentences = MyCorpus()
s_time = time.time()
# gensim word2vec defaults 
# self, sentences=None, corpus_file=None, vector_size=100, alpha=0.025, window=5, min_count=5,
# max_vocab_size=None, sample=1e-3, seed=1, workers=3, min_alpha=0.0001,
# sg=0, hs=0, negative=5, ns_exponent=0.75, cbow_mean=1, hashfxn=hash, epochs=5, null_word=0,
# trim_rule=None, sorted_vocab=1, batch_words=MAX_WORDS_IN_BATCH, compute_loss=False, callbacks=(),
# comment=None, max_final_vocab=None, shrink_windows=True,
mahabharat_model = gensim.models.Word2Vec(sentences=sentences, vector_size=100, alpha=0.025, window=5, epochs=5)
print(f"Time taken to train word2vec model: {time.time() - s_time} seconds")

Time taken to train word2vec model: 8.794673919677734 seconds

In [19]:
my_wv = mahabharat_model.wv
for index, word in enumerate(my_wv.index_to_key):
    if index == 10:
        break
    print(f"word #{index}/{len(my_wv.index_to_key)} is {word}")

word #0/16456 is o
word #1/16456 is thou
word #2/16456 is say
word #3/16456 is king
word #4/16456 is great
word #5/16456 is man
word #6/16456 is thee
word #7/16456 is son
word #8/16456 is art
word #9/16456 is thy

In [21]:
# find similar words 
for word in ["Krishna", "mace", "Bhishma", "Drona", "Pandu"]:
    top_similars = [words for words, _ in my_wv.most_similar(word, topn=10)]
    print(f"{word}: {top_similars}")

Krishna: ['Vasudeva', 'Kesava', 'Govinda', 'Madhava', 'Hrishikesa', 'Panchala', 'Janardana', 'Jishnu', 'Dhananjaya', 'Halayudha']
mace: ['club', 'spiked', 'discus', 'lance', 'uplifted', 'sword', 'scimitar', 'spear', 'axis', 'combatant']
Bhishma: ['Vaisampayana', 'Kanika', 'sringa', 'Sauti', 'Volume', 'XI', 'Vamadeva', 'reharnesse', 'Vyasa', 'Yudhishthira']
Drona: ['pupil', 'Karna', 'Kripa', 'Bharadwaja', 'Phalguna', 'Aswatthaman', 'Salya', 'Saradwata', 'Vikarna', 'Arjuna']
Pandu: ['Pritha', 'Kunti', 'Santanu', 'Vikartana', 'Anadhristi', 'Suta', 'Madri', 'Bidula', 'Vitahavya', 'Asamanjas']

In [22]:
# wv['Arjuna'] - wv['Krishna'] + wv['Duryodhana'] = ?
print(my_wv.most_similar(positive=['Arjuna', 'Duryodhana'], negative=['Krishna'], topn=2))

# wv['Drona'] - wv['Arjuna'] + wv['Drupada'] = ?
print(my_wv.most_similar(positive=['Drona', 'Arjuna'], negative=['Drupada'], topn=2))

# note: due to small size of corpus, analogies won"t be as good as googlenews model

[('charioteer', 0.5584756731987), ('enemy', 0.5102372169494629)]
[('Karna', 0.5533348321914673), ('Gandiva', 0.515582799911499)]